---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/service/superai-app
    eco-base/urn: urn:eco-base:k8s:core:service:superai-app:sha256-23217dadd70dcd0f80f01bc2a5e541d01f9009c71aa5543d7fd1d13d2a18a212
    prometheus.io/path: /metrics
    prometheus.io/port: '8000'
    prometheus.io/scrape: 'true'
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: superai-platform
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/owner: eco-system
    eco-base/platform: core
  name: superai-app
  namespace: eco-superai
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/name: superai-platform
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/audit-log-level: minimal
    eco-base/governance-policy: standard-v1
    eco-base/uri: eco-base://k8s/core/service/superai-app-headless
    eco-base/urn: urn:eco-base:k8s:core:service:superai-app-headless:sha256-b6b04bd30d146c3905dc1039f43be1014545c6cd15d68c4fd8538525ab59a0e7
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: eco-instance
    app.kubernetes.io/name: superai-platform
    app.kubernetes.io/part-of: eco-base
    app.kubernetes.io/version: 1.0.0
    eco-base/environment: development
    eco-base/owner: eco-system
    eco-base/platform: core
  name: superai-app-headless
  namespace: eco-superai
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/name: superai-platform
  type: ClusterIP
