---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/unknown/service/aep-engine-service
    eco-base/urn: urn:eco-base:k8s:unknown:service:aep-engine-service:sha256-d2118744be2d6c2dce72847fc7dcc92e3044356a3c1e12ede8bc134f0c03d0fe
  labels:
    app.kubernetes.io/app.kubernetes.io/component: engine
    app.kubernetes.io/name: aep-engine
    app.kubernetes.io/part-of: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    governance.machinenativeops.io/charter-version: 2.0.0
  name: aep-engine-service
  namespace: platform-03
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: aep-engine
  type: ClusterIP
