---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/unknown/secret/machine-native-ops-secrets
    eco-base/urn: urn:eco-base:k8s:unknown:secret:machine-native-ops-secrets:sha256-b26f7fb6d827d505ab43c0df10a03bf5e1f86a0d80d34dcdf7dfc7d21748d003
  labels: {}
  name: machine-native-ops-secrets
  namespace: platform-03
stringData:
  api-secret-key: change-me-in-production-use-32-chars
  api-signing-key: change-me-in-production-use-64-chars
  aws-access-key-id: ''
  aws-region: us-east-1
  aws-secret-access-key: ''
  database-password: change-me-in-production
  database-url: postgresql://user:password@postgres:5432/machineops
  database-username: machineops_user
  encryption-key: change-me-32-byte-encryption-key-123456
  pagerduty-api-key: ''
  prometheus-basic-auth-password: change-me-in-production
  prometheus-basic-auth-username: prometheus
  signing-key: change-me-64-byte-signing-key-1234567890123456
  slack-webhook-url: ''
  smtp-from: noreply@machinenativeops.com
  smtp-host: smtp.gmail.com
  smtp-password: ''
  smtp-port: '587'
  smtp-username: ''
type: Opaque
