---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/service/file-organizer-service
    eco-base/urn: urn:eco-base:k8s:core:service:file-organizer-service:sha256-dd07dd152ec936b6db5c9f659b4a92907ba23419cc8d93af8563f4935f1bb706
  labels:
    app.kubernetes.io/app.kubernetes.io/component: application
    app.kubernetes.io/name: file-organizer-system
    app.kubernetes.io/part-of: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    governance.machinenativeops.io/charter-version: 2.0.0
  name: file-organizer-service
  namespace: platform-03
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: file-organizer-system
  type: ClusterIP
