---
apiVersion: v1
data:
  JAEGER_AGENT_HOST: jaeger-agent.istio-system.svc.cluster.local
  JAEGER_AGENT_PORT: '6831'
  JAEGER_REPORTER_FLUSH_INTERVAL: 1s
  JAEGER_REPORTER_LOG_SPANS: 'true'
  JAEGER_REPORTER_MAX_QUEUE_SIZE: '1000'
  JAEGER_SAMPLER_PARAM: '0.1'
  JAEGER_SAMPLER_TYPE: probabilistic
  JAEGER_TAGS: environment=production,service=machine-native-ops
  OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger-agent.istio-system.svc.cluster.local
  OTEL_EXPORTER_JAEGER_AGENT_PORT: '6831'
  OTEL_RESOURCE_ATTRIBUTES: service.name=machine-native-ops,deployment.environment=production
  OTEL_SERVICE_NAME: machine-native-ops
kind: ConfigMap
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/unknown/configmap/jaeger-config
    eco-base/urn: urn:eco-base:k8s:unknown:configmap:jaeger-config:sha256-84451a9588fa254161a87f0da83bd3d989f57bc589ea6aaed02ee2f7c955c594
  labels:
    app.kubernetes.io/name: jaeger
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    environment: production
  name: jaeger-config
  namespace: production
---
apiVersion: v1
data:
  tracing.yaml: "enabled: true\nprovider: jaeger\nsampling:\n  type: probabilistic\n\
    \  rate: 0.1\n  environment: production\njaeger:\n  agent:\n    host: jaeger-agent.istio-system.svc.cluster.local\n\
    \    port: 6831\n  collector:\n    endpoint: http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces\n\
    \  sampler:\n    type: probabilistic\n    param: 0.1\n  reporter:\n    logSpans:\
    \ true\n    maxQueueSize: 1000\n    flushInterval: 1s\npropagators:\n  - jaeger\n\
    \  - b3\n  - trace-context\ntags:\n  environment: production\n  service: machine-native-ops\n\
    \  version: v1\nheaders:\n  trace:\n    - uber-trace-id\n    - x-request-id\n\
    \    - x-b3-traceid\n    - x-b3-spanid\n    - x-b3-parentspanid\n    - x-b3-sampled"
kind: ConfigMap
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/unknown/configmap/tracing-config
    eco-base/urn: urn:eco-base:k8s:unknown:configmap:tracing-config:sha256-3ead4b88436f6851b138e07c24b165df5456a5ac09042c9369276f9b5efd9edd
  labels:
    app.kubernetes.io/name: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    environment: production
  name: tracing-config
  namespace: production
