---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/unknown/service/instant-service
    eco-base/urn: urn:eco-base:k8s:unknown:service:instant-service:sha256-dab5a9bcad1a4bd18aa245237b28c5c743897f3b91a9f29d4d5d73ea4c4ad1b7
  labels:
    app.kubernetes.io/app.kubernetes.io/component: data
    app.kubernetes.io/name: instant-system
    app.kubernetes.io/part-of: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    governance.machinenativeops.io/charter-version: 2.0.0
  name: instant-service
  namespace: platform-03
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: instant-system
  type: ClusterIP
