---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/unknown/service/quantumflow-frontend
    eco-base/urn: urn:eco-base:k8s:unknown:service:quantumflow-frontend:sha256-76c55d7c262c492fe5881aba74e8cd1221326aa45f8344cdc99943e85656e9f3
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: quantumflow
    eco-base/governance: aligned
    eco-base/part-of: eco-base
  name: quantumflow-frontend
  namespace: quantumflow
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: quantumflow
  type: ClusterIP
