---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/secret/quantumflow-secrets
    eco-base/urn: urn:eco-base:k8s:core:secret:quantumflow-secrets:sha256-28acecfeb0078b13b6feae2c31360e0c93317efd0808b62416e41cc8168c5000
  labels:
    app.kubernetes.io/name: quantumflow
    eco-base/governance: aligned
    eco-base/part-of: eco-base
  name: quantumflow-secrets
  namespace: quantumflow
stringData:
  ALLOWED_ORIGINS: http://localhost:3000,https://yourdomain.com
  SECRET_KEY: change-me-in-production-use-strong-random-key
type: Opaque
