---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/unknown/service/elasticsearch-search-service
    eco-base/urn: urn:eco-base:k8s:unknown:service:elasticsearch-search-service:sha256-5416f178b7ba2a699f9e734b9c92401081e7d42596f97fa0e3dee0014b7dc18c
  labels:
    app.kubernetes.io/app.kubernetes.io/component: search
    app.kubernetes.io/name: elasticsearch-search-system
    app.kubernetes.io/part-of: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    governance.machinenativeops.io/charter-version: 2.0.0
  name: elasticsearch-search-service
  namespace: platform-03
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: elasticsearch-search-system
  type: ClusterIP
