---
apiVersion: v1
kind: Service
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/service/elasticsearch-search-service
    eco-base/urn: urn:eco-base:k8s:core:service:elasticsearch-search-service:sha256-7597d3bfdba120eac719bd17af78c25f12c345b6eef1d5bfed318257c1bb2c23
  labels:
    app.kubernetes.io/app.kubernetes.io/component: search
    app.kubernetes.io/name: elasticsearch-search-system
    app.kubernetes.io/part-of: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    governance.machinenativeops.io/charter-version: 2.0.0
  name: elasticsearch-search-service
  namespace: platform-03
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: elasticsearch-search-system
  type: ClusterIP
