---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/note: TEMPLATE â€” replace placeholders before applying
    eco-base/owner: platform-team
    eco-base/uri: eco-base://k8s/unknown/secret/argocd-repo-eco-base
    eco-base/urn: urn:eco-base:k8s:unknown:secret:argocd-repo-eco-base:sha256-2d5ebc9dc22ff582d5dfa00aba6d2cde904ac6ec22c3b32b86aa17b0ac2c3174
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: eco-base
    argocd.argoproj.io/secret-type: repository
  name: argocd-repo-eco-base
  namespace: argocd
stringData:
  type: git
  url: https://github.com/indestructibleorg/eco-base
type: Opaque
