---
apiVersion: v1
data:
  CIRCLECI_RUNNER_MODE: single-task
  CIRCLECI_RUNNER_NAME: eco-base-gke-runner
  CIRCLECI_RUNNER_RESOURCE_CLASS: eco/base
  CLEANUP_WORKSPACE: 'true'
  LOG_FORMAT: json
  LOG_LEVEL: info
  POD_CHECK_INTERVAL: 30s
  POD_TIMEOUT: 10m
  WORKING_DIRECTORY: /tmp/circleci-workspace
kind: ConfigMap
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/core/configmap/circleci-agent-config
    eco-base/urn: urn:eco-base:k8s:core:configmap:circleci-agent-config:sha256-3fe2e01b334c56f263daa5324bbbbd99ef25921d5d2c28a4e623be012f954040
  labels:
    app: circleci-runner
  name: circleci-agent-config
  namespace: circleci-runner
