---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/unknown/secret/circleci-runner-secrets
    eco-base/urn: urn:eco-base:k8s:unknown:secret:circleci-runner-secrets:sha256-f203468b58708b02106314422144ba3fc507c76d91e8f7d7b600165152b32fd8
  labels:
    app: circleci-runner
  name: circleci-runner-secrets
  namespace: circleci-runner
stringData:
  CIRCLECI_API_TOKEN: REPLACE_WITH_CIRCLECI_API_TOKEN
  CIRCLECI_RUNNER_TOKEN: REPLACE_WITH_CIRCLECI_RUNNER_TOKEN
type: Opaque
