---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    eco-base/uri: eco-base://k8s/unknown/secret/machine-native-ops-secrets
    eco-base/urn: urn:eco-base:k8s:unknown:secret:machine-native-ops-secrets:sha256-810b2d3e01e1f1e65dee9aea24a9a4c825e3c1082dfbf083113a61cc2c8ea05f
    governance.machinenativeops.io/secret-type: placeholder
  labels:
    app.kubernetes.io/app.kubernetes.io/component: secret
    app.kubernetes.io/name: machine-native-ops
    eco-base/governance: aligned
    eco-base/part-of: eco-base
    governance.machinenativeops.io/charter-version: 2.0.0
  name: machine-native-ops-secrets
  namespace: platform-03
stringData:
  API_KEY: placeholder-replace-with-vault
  DATABASE_PASSWORD: placeholder-replace-with-vault
  GL_TOKEN: placeholder-replace-with-vault
type: Opaque
